server:
  port: 8080
  servlet:
    context-path: /resource-server
keycloak:
  server:

spring:
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/auth/realms/mike
          jwk-set-uri: http://localhost:8091/auth/realms/mike/protocol/openid-connect/certs