
services:
  keycloak-auth-server:
    ports:
      - 9080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    command:
      - start-dev
